### ISSUE TITLE
TypeError: el.querySelectorAll is not a function

### ISSUE THREAD

**Issue by shiv2994** [exupero/saveSvgAsPng#76]
Hey. I have been trying to use the script to implement a download option on a webpage so that the user can download the svg as in image locally. On calling the function `saveSvgAsPng()`, I get the error `TypeError: el.querySelectorAll is not a function` on the console. Could you suggest a solution?
Thanks.

**Comment by exupero** [comment]
It sounds like you might not be passing a DOM element to the function. I've just pushed some error checking. Try the latest version and let me know what you see.

**Comment by shiv2994** [comment]
I tried it again with the latest version. Still getting the same error on the console.

**Comment by exupero** [comment]
What's the value of the first argument you're passing to `saveSvgAsPng`? If it's a DOM element, it should have `querySelectorAll`. If not, what browser are you using? Confirm in the JavaScript console that you're invoking the function with the correct DOM element.

**Comment by shiv2994** [comment]
I am using firefox. I am a little new to SVG so I'm not sure how to go about everything. I have tried to log the svg element in the console before passing it to the saveSvgAsPng function. Should I attach a screenshot of the console log of the svg element so as to give you a better idea?

**Comment by exupero** [comment]
A screenshot might help.

I've also pushed some better error handling code that does a better job of checking for DOM elements. The latest version of the code might give you some more clues.

**Comment by shiv2994** [comment]
Here's a screenshot of the svg element :
![screenshot from 2016-03-16 23 32 21](https://cloud.githubusercontent.com/assets/8582272/13823521/e1f3cdc8-ebcf-11e5-91f7-0c64349e2cce.png)
And thanks for all the help ! :)

**Comment by shiv2994** [comment]
Hey. I made a few changes and tried running it on chrome as well. It's running without any errors. However, it doesn't seem to be doing anything. As in, no image is being saved. I used `console.log()` before and after `saveSvgAsPng()` and both the messages are being displayed so it's certain that the control had been returned to the function from where I had called it.

**Comment by exupero** [comment]
The function has quite a bit of async, so it returns before it's done processing. You'll have to start reaching into the script to find how far it's getting and where it dies.

**Comment by shiv2994** [comment]
Oh, in that case I'll check it out and let you know.

**Comment by exupero** [comment]
Closing due to inactivity.
